CREATE TABLE IF NOT EXISTS FORMS (
    `ID`            BIGINT AUTO_INCREMENT PRIMARY KEY,
    `NAME`          VARCHAR(128) NOT NULL,
    `DISPLAY`       VARCHAR(255),
    `LISTFIELDS`    LONGTEXT,
    `DESCRIPTION`   LONGTEXT
);
CREATE UNIQUE INDEX `UK_FORMS_1` ON `FORMS` (`NAME`);

CREATE TABLE IF NOT EXISTS OPTIONS (
    `ID`            BIGINT AUTO_INCREMENT PRIMARY KEY,
    `FORM`          VARCHAR(128) NOT NULL,
    `FIELD`         VARCHAR(128) NOT NULL,
    `VALUE`         VARCHAR(128) NOT NULL,
    `DISPLAY`       VARCHAR(255) NOT NULL,
    `HIDDEN`        INT NOT NULL DEFAULT 0,
    `DESCRIPTION`   LONGTEXT
);
CREATE UNIQUE INDEX `UK_OPTIONS_1` ON `OPTIONS` (`FIELD`, `FORM`, `VALUE`);

CREATE TABLE IF NOT EXISTS FIELDS (
    `ID`                BIGINT AUTO_INCREMENT PRIMARY KEY,
    `FORM`              VARCHAR(128) NOT NULL,
    `NAME`              VARCHAR(128) NOT NULL,
    `TYPE`              VARCHAR(128) NOT NULL,
    `ORDER`             INT NOT NULL DEFAULT 0,
    `REFERRED`          VARCHAR(128),
    `BLOCKED`           INT NOT NULL DEFAULT 0,
    `HIDDEN`            TINYINT NOT NULL DEFAULT 0,
    `REQUIRED`          TINYINT NOT NULL DEFAULT 0,
    `READONLY`          TINYINT NOT NULL DEFAULT 0,
    `SELECTINPUT`       TINYINT NOT NULL DEFAULT 0,
    `SHOWTITLE`         TINYINT NOT NULL DEFAULT 1,
    `DISPLAY`           VARCHAR(255),
    `DESCRIPTION`       LONGTEXT,
    `HELPTEXT`          LONGTEXT,
    `DEFAULT`           LONGTEXT,
    `VALCHECK`          LONGTEXT,
    `VALCHANGED`        LONGTEXT,
    `REFERREDCOLUMNS`   LONGTEXT
);
CREATE UNIQUE INDEX `UK_FIELDS_1` ON `FIELDS` (`ID`);
CREATE UNIQUE INDEX `UK_FIELDS_2` ON `FIELDS` (`NAME`, `FORM`);

CREATE TABLE IF NOT EXISTS `UNIQUES` (
    `ID`            BIGINT AUTO_INCREMENT PRIMARY KEY,
    `FORM`          VARCHAR(128) NOT NULL,
    `FIELD`         VARCHAR(128) NOT NULL,
    `ORDER`         TINYINT NOT NULL DEFAULT 0,
    `NAME`          VARCHAR(128) NOT NULL DEFAULT 'unique'
);
CREATE UNIQUE INDEX `UK_UNIQUES_1` ON `UNIQUES` (`FORM`, `FIELD`, `NAME`);

CREATE TABLE IF NOT EXISTS ACTIONS (
    `ID`            BIGINT AUTO_INCREMENT PRIMARY KEY,
    `FORM`          VARCHAR(128) NOT NULL,
    `NAME`          VARCHAR(128) NOT NULL,
    `DISPLAY`       VARCHAR(255),
    `PERGROUPS`     VARCHAR(255),
    `CONSCRIPT`     LONGTEXT,
    `PRESCRIPT`     LONGTEXT,
    `VRFSCRIPT`     LONGTEXT,
    `SAVSCRIPT`     LONGTEXT,
    `POSSCRIPT`     LONGTEXT,
    `HELPTEXT`      LONGTEXT,
    `DESCRIPTION`   LONGTEXT
);
CREATE UNIQUE INDEX `UK_ACTIONS_1` ON `ACTIONS` (`FORM`, `NAME`);
